// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/leaderboard/join": {
            "post": {
                "description": "Match a player to a competition or enqueue them",
                "summary": "Join a leaderboard competition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player ID",
                        "name": "player_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Player ID is empty or player not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Player already in competition",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/leaderboard/player/{playerID}": {
            "get": {
                "description": "Get current or last competition for a player",
                "summary": "Get player leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Player ID",
                        "name": "playerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/leaderboard/score": {
            "post": {
                "description": "Add score to the player's current competition",
                "consumes": [
                    "application/json"
                ],
                "summary": "Submit score",
                "parameters": [
                    {
                        "description": "Score submission",
                        "name": "score",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict: no active competition",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/leaderboard/{leaderboardID}": {
            "get": {
                "description": "Get leaderboard by ID",
                "summary": "Get leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Leaderboard ID",
                        "name": "leaderboardID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
